name: Build and Push Docker Images

on:
    push:
      branches:
        - 'main'
        - 'feature/*'
    pull_request:
      branches:
        - 'main'
        - 'feature/*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install backend dependencies
      - name: Install backend dependencies
        run: npm install
        working-directory: api

      # Install frontend dependencies
      - name: Install frontend dependencies
        run: npm install
        working-directory: app/frontend

    #   Run backend test
      - name: Run backend tests
        run: npm test
        working-directory: api

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Express app - ecommerce-backend
        uses: docker/build-push-action@v4
        with:
          context: ./api
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ecommerce-backend:latest

      - name: Build and push React app - ecommerce-frontend
        uses: docker/build-push-action@v4
        with:
          context: ./app/frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ecommerce-frontend:latest